FROM golang:1.24-alpine as builder
WORKDIR /app
COPY . .
RUN go build -o commander ./cmd/commander

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/commander .
EXPOSE 8080
ENTRYPOINT [ "./commander" ]
